spring.application.name=auth-service
server.port=8081
# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://postgres:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# =========================
# JWT
# =========================
jwt.secret=minha-chave-secreta-com-pelo-menos-32-caracteres
jwt.expiration=3600000
# =========================
# LOG
# =========================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO