spring.application.name=pedido-service
server.port=8082
# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:postgresql://postgres:5432/pedidodb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# =========================
# JWT
# =========================
jwt.secret=minha-chave-secreta-com-pelo-menos-32-caracteres
# =========================
# KAFKA
# =========================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=pedido-service
spring.kafka.consumer.auto-offset-reset=earliest
# =========================
# TOPICOS
# =========================
kafka.topic.pedido-criado=pedido.criado
kafka.topic.pagamento-aprovado=pagamento.aprovado
kafka.topic.pagamento-pendente=pagamento.pendente
# =========================
# LOG
# =========================
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO